# Setup
title:               Hotspot Robotics
tagline:             'Always Suspicious'
description:         'A website by and for Guy. '
url:                 https://www.hotspotrobotics.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name: Guy Burroughes

# Gems
plugins:
  - jekyll-paginate
  - jekyll-toc
  - jekyll-numbered-headings

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
